<a href="https://colab.research.google.com/github/MacroAndMicro/-MacroAndMicro/blob/main/matrices_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

## Creation and types of matrices

In [2]:
mat1=np.array([[1,2],[6,7]])
print(mat1)

[[1 2]
 [6 7]]


In [3]:
mat1.shape

(2, 2)

In [4]:
mat2=np.array([[1,2,3],[45,67,89],[-98,-12,-56]])
print(mat2)

[[  1   2   3]
 [ 45  67  89]
 [-98 -12 -56]]


In [5]:
mat2.shape

(3, 3)

### Creating matrices with random values

In [7]:
mat3=np.random.rand(4,4)
print(mat3)

[[0.94119951 0.98468048 0.72210655 0.10067053]
 [0.67217804 0.88442558 0.6130309  0.99730631]
 [0.0349595  0.67376661 0.97716049 0.14894462]
 [0.03883386 0.07048373 0.55504178 0.31695035]]


In [14]:
mat4=np.random.randint(0, 11, size=(4, 5))
print(mat4)

[[ 2  4  3  3  4]
 [ 5  3 10 10  6]
 [ 4  7  1  7  7]
 [ 6  1  5  5  0]]


### Matrix with all values as ones

In [15]:
mato = np.ones((3,3))
print(mato)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
mato = np.ones((3,3), dtype=int)
print(mato)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### Matrix with all values as 0's

In [17]:
mato = np.zeros((3,3))
print(mato)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
mato = np.zeros((3,3), dtype=int)
print(mato)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Identity matrix

In [4]:
mato = np.eye(3,3)
print(mato)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
mato = np.eye(3,3, dtype=int)
print(mato)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Transpose of a matrix

In [9]:
mat4=np.random.randint(0, 11, size=(4, 5))
print(mat4)

[[0 5 1 6 3]
 [2 1 2 6 1]
 [7 8 2 1 7]
 [2 0 9 9 0]]


In [10]:
mata=np.transpose(mat4)
print(mata)

[[0 2 7 2]
 [5 1 8 0]
 [1 2 2 9]
 [6 6 1 9]
 [3 1 7 0]]


## Operations on Matrices



In [15]:
a=np.array([[1,2],[3,4]])
b=np.array([[10,6],[7,8]])

In [16]:
c=a+b
print(c)

[[11  8]
 [10 12]]


In [17]:
c=a-b
print(c)

[[-9 -4]
 [-4 -4]]


In [18]:
z=3
c=z*a
print(c)

[[ 3  6]
 [ 9 12]]


In [19]:
s=np.dot(a,b)
print(s)

[[24 22]
 [58 50]]
